install-and-test: &install-and-test
  - checkout
  - restore_cache:
      key: node-modules-{{ checksum "package-lock.json" }}-{{ checksum "docs/package-lock.json" }}
  - run: npm install && cd docs && npm install
  - save_cache:
      key: node-modules-{{ checksum "package-lock.json" }}-{{ checksum "docs/package-lock.json" }}
      paths:
        - node_modules
        - docs/node_modules
  - run: npm test

version: 2.1
jobs:
  test-node-20: # Maintenance, EOL 2026.04.30
    docker:
      - image: cimg/node:20.19
    steps:
      *install-and-test
  test-node-22: # LTS, EOL 2027.04.30
    docker:
      - image: cimg/node:22.21
    steps:
      *install-and-test
  test-node-24: # Current, EOL 2028.04.30
    docker:
      - image: cimg/node:24.9
    steps:
      *install-and-test
  test-node-lts:
    docker:
      - image: cimg/node:lts
    steps:
      - when:
          condition: true
          steps:
            *install-and-test
      - run: npm run build && cd docs && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - docs/build
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: ./bin/release.sh

test-filters: &test-filters
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build:
    jobs:
      - test-node-20:
          <<: *test-filters
      - test-node-22:
          <<: *test-filters
      - test-node-24:
          <<: *test-filters
      - test-node-lts:
          <<: *test-filters
          requires:
            - test-node-20
            - test-node-22
            - test-node-24
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-(alpha|beta)\.[0-9]+)?/
          requires:
            - test-node-lts
